// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Scraper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928021930_MarkDuplicates")]
    partial class MarkDuplicates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int?>("BoutOrder")
                        .HasColumnType("integer");

                    b.Property<string>("CardSection")
                        .HasColumnType("text");

                    b.Property<int?>("CardSectionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("DuplicateOfBoutId")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fighter1Corner")
                        .HasColumnType("text");

                    b.Property<Guid?>("Fighter1Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Fighter1Name")
                        .HasColumnType("text");

                    b.Property<string>("Fighter1Outcome")
                        .HasColumnType("text");

                    b.Property<string>("Fighter1Slug")
                        .HasColumnType("text");

                    b.Property<string>("Fighter2Corner")
                        .HasColumnType("text");

                    b.Property<Guid?>("Fighter2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Fighter2Name")
                        .HasColumnType("text");

                    b.Property<string>("Fighter2Outcome")
                        .HasColumnType("text");

                    b.Property<string>("Fighter2Slug")
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<int?>("ResultRound")
                        .HasColumnType("integer");

                    b.Property<string>("ResultTime")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<bool>("TitleBout")
                        .HasColumnType("boolean");

                    b.Property<string>("WeightClass")
                        .HasColumnType("text");

                    b.Property<Guid?>("WinnerFighterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Fighter1Id");

                    b.HasIndex("Fighter2Id");

                    b.HasIndex("WinnerFighterId");

                    b.ToTable("Bouts");
                });

            modelBuilder.Entity("BoutFighterStats", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("BodyAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("BodyLanded")
                        .HasColumnType("integer");

                    b.Property<string>("BoutId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClinchAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("ClinchLanded")
                        .HasColumnType("integer");

                    b.Property<string>("ControlTime")
                        .HasColumnType("text");

                    b.Property<int>("DistanceAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceLanded")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FighterId")
                        .HasColumnType("uuid");

                    b.Property<string>("FighterSlug")
                        .HasColumnType("text");

                    b.Property<int>("GroundAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("GroundLanded")
                        .HasColumnType("integer");

                    b.Property<int>("HeadAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("HeadLanded")
                        .HasColumnType("integer");

                    b.Property<int>("Knockdowns")
                        .HasColumnType("integer");

                    b.Property<int>("LegAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("LegLanded")
                        .HasColumnType("integer");

                    b.Property<int>("Reversals")
                        .HasColumnType("integer");

                    b.Property<int>("SigStrikesAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("SigStrikesLanded")
                        .HasColumnType("integer");

                    b.Property<int>("SubmissionAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("TakedownsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TakedownsLanded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStrikesAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStrikesLanded")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoutId");

                    b.HasIndex("FighterId");

                    b.ToTable("BoutFighterStats");
                });

            modelBuilder.Entity("Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasJsonPropertyName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasJsonPropertyName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("createdAt");

                    b.Property<double?>("DataAgeHours")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("dataAgeHours");

                    b.Property<DateTime?>("DataFreshness")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("dataFreshness");

                    b.Property<string>("DataId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("dataId");

                    b.Property<string>("DataSource")
                        .HasColumnType("text")
                        .HasJsonPropertyName("dataSource");

                    b.Property<Guid?>("DuplicateOfEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("eventDate");

                    b.Property<string>("EventDateLabel")
                        .HasColumnType("text")
                        .HasJsonPropertyName("eventDateLabel");

                    b.Property<string>("EventTimeZone")
                        .HasColumnType("text")
                        .HasJsonPropertyName("eventTimeZone");

                    b.Property<string>("EventWeekday")
                        .HasColumnType("text")
                        .HasJsonPropertyName("eventWeekday");

                    b.Property<string>("FreshnessStatus")
                        .HasColumnType("text")
                        .HasJsonPropertyName("freshnessStatus");

                    b.Property<bool>("HasStats")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("hasStats");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("lastSyncedAt");

                    b.Property<string>("LocationText")
                        .HasColumnType("text")
                        .HasJsonPropertyName("locationText");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ShortTitle")
                        .HasColumnType("text")
                        .HasJsonPropertyName("shortTitle");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasJsonPropertyName("slug");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("startsAt");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasJsonPropertyName("state");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasJsonPropertyName("title");

                    b.Property<string>("Venue")
                        .HasColumnType("text")
                        .HasJsonPropertyName("venue");

                    b.Property<DateTime?>("VenueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("venueDate");

                    b.Property<string>("VenueDateLabel")
                        .HasColumnType("text")
                        .HasJsonPropertyName("venueDateLabel");

                    b.Property<string>("VenueTimeZone")
                        .HasColumnType("text")
                        .HasJsonPropertyName("venueTimeZone");

                    b.Property<string>("VenueWeekday")
                        .HasColumnType("text")
                        .HasJsonPropertyName("venueWeekday");

                    b.Property<string>("Warning")
                        .HasColumnType("text")
                        .HasJsonPropertyName("warning");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("age");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasJsonPropertyName("bio");

                    b.Property<string>("ChampionStatus")
                        .HasColumnType("text")
                        .HasJsonPropertyName("championStatus");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasJsonPropertyName("country");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasJsonPropertyName("division");

                    b.Property<string>("FightingStyle")
                        .HasColumnType("text")
                        .HasJsonPropertyName("fightingStyle");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("firstName");

                    b.Property<string>("HeightInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("heightInches");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isActive");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("lastName");

                    b.Property<string>("LegReachInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("legReachInches");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasJsonPropertyName("nickname");

                    b.Property<DateTime?>("OctagonDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("octagonDebut");

                    b.Property<int?>("P4pRank")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("p4pRank");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasJsonPropertyName("placeOfBirth");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profileUrl");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReachInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("reachInches");

                    b.Property<int?>("RecordDraws")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordDraws");

                    b.Property<int?>("RecordLosses")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordLosses");

                    b.Property<int?>("RecordNoContest")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordNoContest");

                    b.Property<string>("RecordText")
                        .HasColumnType("text")
                        .HasJsonPropertyName("recordText");

                    b.Property<int?>("RecordWins")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordWins");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasJsonPropertyName("slug");

                    b.Property<string>("Stance")
                        .HasColumnType("text")
                        .HasJsonPropertyName("stance");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.Property<string>("TrainsAt")
                        .HasColumnType("text")
                        .HasJsonPropertyName("trainsAt");

                    b.Property<string>("UfcStatsId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ufcStatsId");

                    b.Property<string>("WeightLbs")
                        .HasColumnType("text")
                        .HasJsonPropertyName("weightLbs");

                    b.HasKey("Id");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("FighterHeroStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FighterId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FighterId");

                    b.ToTable("FighterHeroStats");
                });

            modelBuilder.Entity("FighterStats", b =>
                {
                    b.Property<Guid>("FighterId")
                        .HasColumnType("uuid");

                    b.Property<int>("AverageFightTimeSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("BodyStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ClinchStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GroundStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HeadStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KnockdownAvg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LegStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SigStrikesAbsorbedPerMin")
                        .HasColumnType("numeric");

                    b.Property<int>("SigStrikesAttempted")
                        .HasColumnType("integer");

                    b.Property<decimal>("SigStrikesDefense")
                        .HasColumnType("numeric");

                    b.Property<int>("SigStrikesLanded")
                        .HasColumnType("integer");

                    b.Property<decimal>("SigStrikesLandedPerMin")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StandingStrikePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StrikingAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SubmissionAvgPer15Min")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakedownAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakedownAvgPer15Min")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TakedownDefense")
                        .HasColumnType("numeric");

                    b.Property<int>("TakedownsAttempted")
                        .HasColumnType("integer");

                    b.Property<int>("TakedownsLanded")
                        .HasColumnType("integer");

                    b.HasKey("FighterId");

                    b.ToTable("FighterStats");
                });

            modelBuilder.Entity("Bout", b =>
                {
                    b.HasOne("Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fighter", null)
                        .WithMany()
                        .HasForeignKey("Fighter1Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fighter", null)
                        .WithMany()
                        .HasForeignKey("Fighter2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fighter", null)
                        .WithMany()
                        .HasForeignKey("WinnerFighterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BoutFighterStats", b =>
                {
                    b.HasOne("Bout", null)
                        .WithMany()
                        .HasForeignKey("BoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fighter", null)
                        .WithMany()
                        .HasForeignKey("FighterId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FighterHeroStat", b =>
                {
                    b.HasOne("Fighter", null)
                        .WithMany("HeroStatRows")
                        .HasForeignKey("FighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FighterStats", b =>
                {
                    b.HasOne("Fighter", null)
                        .WithOne("Stats")
                        .HasForeignKey("FighterStats", "FighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Navigation("HeroStatRows");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
