// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Scraper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719064531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasJsonPropertyName("id");

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("age");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasJsonPropertyName("bio");

                    b.Property<string>("ChampionStatus")
                        .HasColumnType("text")
                        .HasJsonPropertyName("championStatus");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasJsonPropertyName("country");

                    b.Property<string>("Division")
                        .HasColumnType("text")
                        .HasJsonPropertyName("division");

                    b.Property<string>("FightingStyle")
                        .HasColumnType("text")
                        .HasJsonPropertyName("fightingStyle");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("firstName");

                    b.Property<string>("HeightInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("heightInches");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("imageUrl");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("isActive");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasJsonPropertyName("lastName");

                    b.Property<string>("LegReachInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("legReachInches");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasJsonPropertyName("nickname");

                    b.Property<DateTime?>("OctagonDebut")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("octagonDebut");

                    b.Property<int?>("P4pRank")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("p4pRank");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("text")
                        .HasJsonPropertyName("placeOfBirth");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text")
                        .HasJsonPropertyName("profileUrl");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ReachInches")
                        .HasColumnType("text")
                        .HasJsonPropertyName("reachInches");

                    b.Property<int?>("RecordDraws")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordDraws");

                    b.Property<int?>("RecordLosses")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordLosses");

                    b.Property<int?>("RecordNoContest")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordNoContest");

                    b.Property<string>("RecordText")
                        .HasColumnType("text")
                        .HasJsonPropertyName("recordText");

                    b.Property<int?>("RecordWins")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("recordWins");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasJsonPropertyName("slug");

                    b.Property<string>("Stance")
                        .HasColumnType("text")
                        .HasJsonPropertyName("stance");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasJsonPropertyName("status");

                    b.Property<string>("TrainsAt")
                        .HasColumnType("text")
                        .HasJsonPropertyName("trainsAt");

                    b.Property<string>("UfcStatsId")
                        .HasColumnType("text")
                        .HasJsonPropertyName("ufcStatsId");

                    b.Property<string>("WeightLbs")
                        .HasColumnType("text")
                        .HasJsonPropertyName("weightLbs");

                    b.HasKey("Id");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("FighterHeroStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FighterId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FighterId");

                    b.ToTable("FighterHeroStats");
                });

            modelBuilder.Entity("FighterHeroStat", b =>
                {
                    b.HasOne("Fighter", null)
                        .WithMany("HeroStatRows")
                        .HasForeignKey("FighterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fighter", b =>
                {
                    b.Navigation("HeroStatRows");
                });
#pragma warning restore 612, 618
        }
    }
}
